"""Add password methods to Admin

Revision ID: 6c835fdffdef
Revises: 
Create Date: 2025-04-10 08:21:40.554811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c835fdffdef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('suggestion', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('suggestion', sa.Column('ip_hash', sa.String(length=64), nullable=True))

    op.create_foreign_key('fk_admin_created_by', 'admin', 'admin', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_admin_created_by', 'admin', type_='foreignkey')

    op.drop_column('suggestion', 'ip_hash')
    op.drop_column('suggestion', 'name')
    op.drop_column('suggestion', 'phone')
    # ### end Alembic commands ###
